name: CI

# allow also running manually
on: ["push", "pull_request", "workflow_dispatch"]

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        node-version: ["20.x"]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Build the application
        run: npm run build

      - name: Run ESLint
        run: npm run eslint

      - name: Run prune check
        run: |
          echo "The following is a list of unused exports that need to be removed:"
          npm run prune

      - name: Create archive
        if: github.event_name == 'push'
        run: tar -czf ${{ github.sha }}.tar.gz dist

      - name: Release on push to branch
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v3
        with:
          # for a fork PR is the fork itself: owner/fork-name
          repository: ${{ github.repository }}
          tag_name: ${{ github.ref_name }}
          name: "Build of branch ${{ github.ref_name }}"
          files: ${{ github.sha }}.tar.gz
